/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPegProxy, IPegProxyInterface } from "../IPegProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "chainID",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burnBoringToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPegProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IPegProxyInterface {
    return new utils.Interface(_abi) as IPegProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPegProxy {
    return new Contract(address, _abi, signerOrProvider) as IPegProxy;
  }
}
