/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SafeDecimalMath,
  SafeDecimalMathInterface,
} from "../SafeDecimalMath";

const _abi = [
  {
    inputs: [],
    name: "PRECISE_UNIT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "UNIT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "highPrecisionDecimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "preciseUnit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "unit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x61024761003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361061006c5760003560e01c8063313ce56714610071578063864029e714610090578063907af6c0146100a65780639d8e2177146100ae578063d5e5e6e6146100b6578063def4419d146100be575b600080fd5b610079601281565b60405160ff90911681526020015b60405180910390f35b6100986100c6565b604051908152602001610087565b6100986100d5565b6100986100e8565b6100986100f4565b610079601b81565b6100d2601b600a610145565b81565b60006100e36012600a610145565b905090565b6100d26012600a610145565b60006100e3601b600a610145565b600181815b8085111561013d578160001904821115610123576101236101fb565b8085161561013057918102915b93841c9390800290610107565b509250929050565b60006101518383610158565b9392505050565b600082610167575060016101f5565b81610174575060006101f5565b816001811461018a5760028114610194576101b0565b60019150506101f5565b60ff8411156101a5576101a56101fb565b50506001821b6101f5565b5060208310610133831016604e8410600b84101617156101d3575081810a6101f5565b6101dd8383610102565b80600019048211156101f1576101f16101fb565b0290505b92915050565b634e487b7160e01b600052601160045260246000fdfea2646970667358221220ef0f3f9749b4c333a1557e7fd3500b0ecb101d2b625253d7792eedc93048407964736f6c63430008040033";

export class SafeDecimalMath__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SafeDecimalMath> {
    return super.deploy(overrides || {}) as Promise<SafeDecimalMath>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SafeDecimalMath {
    return super.attach(address) as SafeDecimalMath;
  }
  connect(signer: Signer): SafeDecimalMath__factory {
    return super.connect(signer) as SafeDecimalMath__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SafeDecimalMathInterface {
    return new utils.Interface(_abi) as SafeDecimalMathInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SafeDecimalMath {
    return new Contract(address, _abi, signerOrProvider) as SafeDecimalMath;
  }
}
