/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IPegSwapInterface extends ethers.utils.Interface {
  functions: {
    "getMaxToken0AmountOut(address,uint256)": FunctionFragment;
    "getMaxToken1AmountOut(address,uint256)": FunctionFragment;
    "getPair(address,uint256)": FunctionFragment;
    "swapToken0ForToken1(address,uint256,uint256,address)": FunctionFragment;
    "swapToken1ForToken0(address,uint256,uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getMaxToken0AmountOut",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxToken1AmountOut",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPair",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapToken0ForToken1",
    values: [string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "swapToken1ForToken0",
    values: [string, BigNumberish, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMaxToken0AmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxToken1AmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapToken0ForToken1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapToken1ForToken0",
    data: BytesLike
  ): Result;

  events: {};
}

export class IPegSwap extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPegSwapInterface;

  functions: {
    getMaxToken0AmountOut(
      token0: string,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMaxToken1AmountOut(
      token0: string,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPair(
      token: string,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    swapToken0ForToken1(
      token0: string,
      chainID: BigNumberish,
      amountIn: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapToken1ForToken0(
      token0: string,
      chainID: BigNumberish,
      amountIn: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getMaxToken0AmountOut(
    token0: string,
    chainID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMaxToken1AmountOut(
    token0: string,
    chainID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPair(
    token: string,
    chainID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  swapToken0ForToken1(
    token0: string,
    chainID: BigNumberish,
    amountIn: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapToken1ForToken0(
    token0: string,
    chainID: BigNumberish,
    amountIn: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getMaxToken0AmountOut(
      token0: string,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMaxToken1AmountOut(
      token0: string,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPair(
      token: string,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    swapToken0ForToken1(
      token0: string,
      chainID: BigNumberish,
      amountIn: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    swapToken1ForToken0(
      token0: string,
      chainID: BigNumberish,
      amountIn: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getMaxToken0AmountOut(
      token0: string,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMaxToken1AmountOut(
      token0: string,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPair(
      token: string,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapToken0ForToken1(
      token0: string,
      chainID: BigNumberish,
      amountIn: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapToken1ForToken0(
      token0: string,
      chainID: BigNumberish,
      amountIn: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getMaxToken0AmountOut(
      token0: string,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaxToken1AmountOut(
      token0: string,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPair(
      token: string,
      chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapToken0ForToken1(
      token0: string,
      chainID: BigNumberish,
      amountIn: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapToken1ForToken0(
      token0: string,
      chainID: BigNumberish,
      amountIn: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
